sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LgzQxKG8X1RDtkw6LRK9VgWE6aes2p/u8SaFS4mSRX+7RDhl3seWa1BdbE0I6R3Ct328KTKy3z6ENJQLZn/qzMhvLxS1aYwvmhNY2lVWpXDOXfe7QJZzz0vAY7bkzlq8lZ1MXTnkGOy4+KQeczyw9iJ+Rii9BlWvZsyLkmm4WCecWOxIurfXivjDXylo3x58K6opZC7jPbVDZx1QxJbkTkOZxbWt2Hf/8jNN/2fJIuqW7WAZUULDKpt8jWRZWmY6YdKgj0l2ptcXGKp8kCgJw5ZOvkyPi2+QHDxyrEj1qx/6GYN2fUWJpkdPxWVvT2tCAIgbktElStJVSbUuLZVFe01Hn84UcibR320ehLoF8P/UnoC0q9yThDv/09yPTHGiVBIeGlSGqbPF+mPiM8t61j70hTR83gASyi82XlPf7JpoGjerLHz/Wa9EVb+lT52liJbxW2Knlxm/r/O2X9JJW95rFCTGT0ZF/w7zI102lynTlM6rHgZylwCGajltvb8dGJJGFOYbPM1mHifzTud46vPiEsk7bHKkW1FUM8X6CHdA/Jnbx2o/HrF0XoLJTblYERx1uvEA7sq/lmsCRVnc1jXkQ9U3bHkIrffppk886dN1Q966RvnP8I2wwSLw05NYUZNP/OFm0ZNS1wOxUcYLOB27Qq8KjwcT//ifGXYnPKw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Call-of-the-Wild_215
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy